name: hotel_ai_app
description: "A professional AI-powered hotel receptionist app with modern UI design and comprehensive features."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/hotel_bg.jpg
    - assets/hotel_logo.png
